update

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -104,7 +104,7 @@ jobs:
               if: always()
               run: sf org delete scratch -p -o test-scratch-org
 
-    build-package:
+    deploy-qa/uat/sit:
         runs-on: ubuntu-latest
         needs: scratch-org-test
         steps:
@@ -126,6 +126,9 @@ jobs:
             - name: "List"
               run: ls ./release
 
+            - name: "Deploy to QA/UAT/SIT"
+              run: echo "No Sandbox to deploy... Skip..."
+
     release-package-version:
         runs-on: ubuntu-latest
         needs: scratch-org-test
@@ -141,6 +144,21 @@ jobs:
                   nodeInstallPath=$(npm config get prefix)
                   echo "$nodeInstallPath/bin" >> $GITHUB_PATH
                   sf --version
+
+            # Store secret for dev hub
+            - name: 'Populate auth file with DEVHUB_SFDX_URL secret'
+              shell: bash
+              run: |
+                  echo ${{ secrets.DEVHUB_SFDX_URL }} > ./DEVHUB_SFDX_URL.txt
+                  secretFileSize=$(wc -c "./DEVHUB_SFDX_URL.txt" | awk '{print $1}')
+                  if [ $secretFileSize == 1 ]; then
+                      echo "Missing DEVHUB_SFDX_URL secret. Is this workflow running on a fork?";
+                      exit 1;
+                  fi
+
+            # Authenticate dev hub
+            - name: 'Authenticate Dev Hub'
+              run: sf org login sfdx-url -f ./DEVHUB_SFDX_URL.txt -a devhub -d
 
             # Create package version and extract its id
             - name: 'Create package version'
