update

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -81,7 +81,7 @@ jobs:
 
             # Create scratch org
             - name: 'Create scratch org'
-              run: sf org create scratch -f config/project-scratch-def.json -a scratch-org -d -y 1
+              run: sf org create scratch -f config/project-scratch-def.json -a test-scratch-org -d -y 1
 
             # Deploy source to scratch org
             - name: 'Push source to scratch org'
@@ -102,7 +102,7 @@ jobs:
             # Housekeeping
             - name: 'Delete scratch org'
               if: always()
-              run: sf org delete scratch -p -o scratch-org
+              run: sf org delete scratch -p -o test-scratch-org
 
     build-package:
         runs-on: ubuntu-latest
@@ -126,7 +126,7 @@ jobs:
             - name: "List"
               run: ls ./release
 
-    create-package-version:
+    release-package-version:
         runs-on: ubuntu-latest
         needs: scratch-org-test
         steps:
@@ -142,5 +142,38 @@ jobs:
                   echo "$nodeInstallPath/bin" >> $GITHUB_PATH
                   sf --version
 
-            - name: "Convert source"
-              run: sf package version create -p 0HodL0000000kFlSAI -x -w 20 -f config/project-scratch-def.json --json
+            # Create package version and extract its id
+            - name: 'Create package version'
+              id: createPackageVersion
+              run: |
+                  set +e
+                  json=$(sf package version create -p DreamhouseLWC -x -w 20 -f config/project-scratch-def.json --json)
+                  echo $json
+                  status=$(echo $json | jq '.status')
+                  if [ $status == "0" ]; then
+                      packageVersionId=$(echo $json | jq -r '.result.SubscriberPackageVersionId')
+                      echo "packageVersionId=$packageVersionId" >> $GITHUB_OUTPUT
+                  else
+                      echo "Failed to create package version"
+                  fi
+                  exit $status
+
+            # Wait for package replication
+            - name: 'Wait for package replication'
+              run: sleep 360s
+
+            # Create scratch org
+            - name: 'Create scratch org'
+              run: sf org create scratch -f config/project-scratch-def.json -a uat-scratch-org -d -y 1
+
+            # Install new package in scratch org
+            - name: 'Install new package version in scratch org'
+              run: sf package install -p ${{ steps.createPackageVersion.outputs.packageVersionId }} -w 10 -o uat-scratch-org -r
+
+            # Update package install link in readme
+            - name: 'Update package install link in readme'
+              run: |
+                  packageVersionId="${{ steps.createPackageVersion.outputs.packageVersionId }}"
+                  packageLinkRegex="https:\/\/login\.salesforce\.com\/packaging\/installPackage\.apexp\?p0=[a-zA-ZA-ZA-Z0-9]{18}"
+                  newPackageLink="https://login.salesforce.com/packaging/installPackage.apexp?p0=${packageVersionId}"
+                  echo $newPackageLink
